---
services:
  traefik:
    image: traefik:v2.4.7
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./docker/traefik/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro
      - ./docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './apps/back/public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`blog.app.localhost`)"
      - "traefik.http.routers.back.tls=true"
    restart: unless-stopped

  php:
    build:
      context: apps/back
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./apps/back:/usr/src/app:rw
    restart: unless-stopped

  front:
    build:
      context: apps/front
      dockerfile: Dockerfile
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`blog.app.localhost`) && (
        PathPrefix(`/react`) ||
        PathPrefix(`/articles`)
      )"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
    volumes:
      - ./apps/front:/usr/src/app:rw
    restart: unless-stopped

networks:
  proxy:
    external: true
