---
version: '3.8'

services:
  traefik:
    build:
      context: apps/traefik
      dockerfile: Dockerfile
    container_name: traefik
    ports:
      - 80:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    restart: unless-stopped

  nginx:
    build:
      context: apps/nginx
      dockerfile: Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.back.rule=Host(`blog.app.localhost`)'
    restart: unless-stopped

  php:
    build:
      context: apps/back
      dockerfile: Dockerfile
      target: dev
    volumes:
      - './apps/back:/usr/src/app:rw'
    environment:
      FRONTEND_HOST: 'http://blog.app.localhost'
    restart: unless-stopped

  front:
    build:
      context: apps/front
      dockerfile: Dockerfile
      target: dev
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.front.rule=Host(`blog.app.localhost`) && (
        PathPrefix(`/react`) ||
        PathPrefix(`/articles`)
      )'
      - 'traefik.http.services.front.loadbalancer.server.port=3000'
    environment:
      REACT_APP_SYMFONY_HOST: 'http://blog.app.localhost'
      REACT_APP_API_URL: 'http://blog.app.localhost/api'
      WDS_SOCKET_PATH: '/react/sockjs-node'
    volumes:
      - './apps/front:/usr/src/app:rw'
    restart: unless-stopped
